[local]
localhost

[mongodb]
mongodb.exptrack.shop

[redis]
redis.exptrack.shop 

[mysql]
mysql.exptrack.shop

[rabbitmq]
rabbitmq.exptrack.shop  

[catalogue]
catalogue.exptrack.shop

[user]
user.exptrack.shop

[cart]
cart.exptrack.shop

[shipping]
shipping.exptrack.shop

[payment]
payment.exptrack.shop

[frontend]
frontend.exptrack.shop