
- name: install mysql server
  package:
    name: mysql-server
    state: present

- name: start and enbale services
  service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password
  command:  mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"